[workspace]
resolver = "2"

members = [
  "cli",
  "lib",
]

[workspace.dependencies]
anyhow = "1.0.75"
clap = "4.4.1"
globset = "0.4.9"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
walkdir = "2.3.3"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
