[workspace]
resolver = "2"

members = [
  "cli",
  "lib",
]

[workspace.dependencies]
anyhow = "1.0.100"
clap = "4.5.50"
globset = "0.4.18"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
